name: 'Get and cache dependencies'
desctipion: 'Gets the dependencies (for npm) and caches them.'
inputs:
  caching:
    description: 'Whether to cache dependenies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.set-output.outputs.used-cache }}
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Set Output
      id: set-output
      run: echo "used-cache=${{inputs.caching}}" >> "$GITHUB_OUTPUT"
      shell: bash